import PeriodSchema from 'schemas/PeriodSchema';

enum Types {
  GET_PERIODS = 'PERIOD/GET_PERIODS',
  GET_PERIODS_ERROR = 'PERIOD/GET_PERIODS_ERROR',
  GET_PERIODS_SUCCESS = 'PERIOD/GET_PERIODS_SUCCESS',
  SET_OLD_PERIODS = 'PERIOD/SET_OLD_PERIODS',
  SET_OLD_PERIODS_ERROR = 'PERIOD/SET_OLD_PERIODS_ERROR',
  SET_OLD_PERIODS_SUCCESS = 'PERIOD/SET_OLD_PERIODS_SUCCESS',
  SET_BEGIN = 'PERIOD/SET_BEGIN',
  SET_BEGIN_ERROR = 'PERIOD/SET_BEGIN_ERROR',
  SET_BEGIN_SUCCESS = 'PERIOD/SET_BEGIN_SUCCESS',
  SET_END = 'PERIOD/SET_END',
  SET_END_ERROR = 'PERIOD/SET_END_ERROR',
  SET_END_SUCCESS = 'PERIOD/SET_END_SUCCESS',
  SET_DAY_SYMPTOMS = 'PERIOD/SET_DAY_SYMPTOMS',
  SET_DAY_SYMPTOMS_ERROR = 'PERIOD/SET_DAY_SYMPTOMS_ERROR',
  SET_DAY_SYMPTOMS_SUCCESS = 'PERIOD/SET_DAY_SYMPTOMS_SUCCESS',
}
export interface PeriodState {
  readonly loading: boolean;
  readonly period: PeriodSchema[] | undefined;
  readonly error: boolean;
}

export default Types;
